version: '3.8'

services:
  app:
    build: .
    image: gestor-financeiro:latest
    # env_file:
    #   - .env
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_MAIL_HOST=${EMAIL_HOST}
      - SPRING_MAIL_PORT=${EMAIL_PORT}
      - SPRING_MAIL_USERNAME=${EMAIL_SENDER}
      - TZ=America/Sao_Paulo
    ports:
      - "3001:3001"
    restart: always
