version: '3.8'

services:
  app:
    build: .
    image: gestor-financeiro:latest

    environment:
      # Banco de dados
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

      # Email
      - SPRING_MAIL_HOST=${EMAIL_HOST}
      - SPRING_MAIL_PORT=${EMAIL_PORT}.
      - SPRING_MAIL_USERNAME=${EMAIL_SENDER}
      - EMAIL_SENDER=${EMAIL_SENDER}

      # AWS
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET={$AWS_S3_BUCKET}

      # Timezone
      - TZ=America/Sao_Paulo

    ports:
      - "3001:3001"

    restart: always
